In [2]:
# 1. 모듈 연결하기
import requests
import pandas as pd
import json

In [4]:
# 2. 기본정보 설정
url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'
params ={'serviceKey' : 'V2soxVa/BMDzYDIk9IbGZTgcZeSQ6GIdaZnsBoez7GPAUwIQ/6MT/jyI5mtbTgXy24zNvlE9d5/EF0Y0YoKoNQ==', 
         'pageNo' : '1', 
         'numOfRows' : '10', 
         'dataType' : 'JSON', 
         'dataCd' : 'ASOS', 
         'dateCd' : 'DAY', 
         'startDt' : '20100101', 
         'endDt' : '20100806', 
         'stnIds' : '108' }

In [13]:
# 지점명을 이용한 지점코드 찾기
def loc_code_sch(loc_name):
    loc_code = pd.read_csv('./기상청위치코드.csv', encoding='utf-8')
    loc_code=loc_code[loc_code['지점명']==loc_name]['지점'].values[0]
    return str(loc_code)

In [20]:
# 3. 사용자 검색 옵션 입력 및 지역 코드 확인
startDT = input('시작일자를 입력하세요(yyyymmdd): ')
endDT= input('종료일자를 입력하세요(yyyymmdd): ')
location= input('지역을 입력하세요: ')
loc_code=loc_code_sch(location)

In [22]:
# 4. 사용자가 입력받은 조건으로 기상청에 데이터 요청하기
params['startDt'] = startDT
params['endDt'] = endDT
params['stnIds'] = loc_code

params

{'serviceKey': 'V2soxVa/BMDzYDIk9IbGZTgcZeSQ6GIdaZnsBoez7GPAUwIQ/6MT/jyI5mtbTgXy24zNvlE9d5/EF0Y0YoKoNQ==',
 'pageNo': '1',
 'numOfRows': '10',
 'dataType': 'JSON',
 'dataCd': 'ASOS',
 'dateCd': 'DAY',
 'startDt': '20230101',
 'endDt': '20230806',
 'stnIds': '155'}

In [23]:
# 5. 기상청 조회 일자별 데이터 가져오기
response = requests.get(url, params=params)

weather = json.loads(response.content)
weather

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL_SERVICE'},
  'body': {'dataType': 'JSON',
   'items': {'item': [{'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-01',
      'avgTa': '2.4',
      'minTa': '-3.0',
      'minTaHrmt': '0544',
      'maxTa': '7.2',
      'maxTaHrmt': '1443',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '6.2',
      'maxInsWsWd': '20',
      'maxInsWsHrmt': '1347',
      'maxWs': '4.0',
      'maxWsWd': '50',
      'maxWsHrmt': '1348',
      'avgWs': '1.3',
      'hr24SumRws': '1087',
      'maxWd': '50',
      'avgTd': '-9.0',
      'minRhm': '21',
      'minRhmHrmt': '2025',
      'avgRhm': '45.1',
      'avgPv': '3.2',
      'avgPa': '1024.4',
      'maxPs': '1030.6',
      'maxPsHrmt': '0954',
      'minPs': '1026.4',
      'minPsHrmt': '1536',
      'avgPs': '1028.9',
      'ssDur': '9.8',
      'sumSsHr': '8.5',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.72',
      'sumGsr': '9.24',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '1.9',
      'avgLmac': '0.0',
      'avgTs': '0.3',
      'minTg': '-7.7',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.7',
      'sumSmlEv': '2.4',
      'n99Rn': '',
      'iscs': '{연무}1334-{연무}{강도0}1500-1756.',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-02',
      'avgTa': '1.3',
      'minTa': '-0.9',
      'minTaHrmt': '2356',
      'maxTa': '4.6',
      'maxTaHrmt': '1538',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '7.5',
      'maxInsWsWd': '50',
      'maxInsWsHrmt': '1130',
      'maxWs': '5.2',
      'maxWsWd': '50',
      'maxWsHrmt': '1241',
      'avgWs': '1.7',
      'hr24SumRws': '1467',
      'maxWd': '50',
      'avgTd': '-18.9',
      'minRhm': '12',
      'minRhmHrmt': '1540',
      'avgRhm': '21.1',
      'avgPv': '1.4',
      'avgPa': '1024.4',
      'maxPs': '1030.9',
      'maxPsHrmt': '0955',
      'minPs': '1026.6',
      'minPsHrmt': '1528',
      'avgPs': '1028.9',
      'ssDur': '9.9',
      'sumSsHr': '8.4',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.88',
      'sumGsr': '11.16',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '4.9',
      'avgLmac': '1.3',
      'avgTs': '0.9',
      'minTg': '-6.9',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '2.0',
      'sumSmlEv': '2.8',
      'n99Rn': '',
      'iscs': '',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-03',
      'avgTa': '0.4',
      'minTa': '-2.7',
      'minTaHrmt': '0736',
      'maxTa': '4.9',
      'maxTaHrmt': '1303',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '7.0',
      'maxInsWsWd': '50',
      'maxInsWsHrmt': '1117',
      'maxWs': '4.4',
      'maxWsWd': '50',
      'maxWsHrmt': '1135',
      'avgWs': '1.7',
      'hr24SumRws': '1454',
      'maxWd': '360',
      'avgTd': '-15.2',
      'minRhm': '19',
      'minRhmHrmt': '1300',
      'avgRhm': '30.8',
      'avgPv': '1.9',
      'avgPa': '1023.4',
      'maxPs': '1029.5',
      'maxPsHrmt': '1006',
      'minPs': '1026.0',
      'minPsHrmt': '1547',
      'avgPs': '1027.8',
      'ssDur': '9.9',
      'sumSsHr': '8.6',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.96',
      'sumGsr': '11.24',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '1.4',
      'avgLmac': '0.0',
      'avgTs': '0.2',
      'minTg': '-6.3',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.9',
      'sumSmlEv': '2.7',
      'n99Rn': '',
      'iscs': '',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-04',
      'avgTa': '1.8',
      'minTa': '-3.7',
      'minTaHrmt': '0701',
      'maxTa': '8.0',
      'maxTaHrmt': '1356',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '7.8',
      'maxInsWsWd': '50',
      'maxInsWsHrmt': '0223',
      'maxWs': '4.9',
      'maxWsWd': '50',
      'maxWsHrmt': '0225',
      'avgWs': '1.7',
      'hr24SumRws': '1450',
      'maxWd': '50',
      'avgTd': '-11.7',
      'minRhm': '29',
      'minRhmHrmt': '0514',
      'avgRhm': '36.1',
      'avgPv': '2.6',
      'avgPa': '1024.9',
      'maxPs': '1030.7',
      'maxPsHrmt': '2249',
      'minPs': '1027.2',
      'minPsHrmt': '1512',
      'avgPs': '1029.3',
      'ssDur': '9.9',
      'sumSsHr': '8.6',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.84',
      'sumGsr': '10.32',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '0.0',
      'avgLmac': '0.0',
      'avgTs': '0.5',
      'minTg': '-8.3',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.6',
      'sumSmlEv': '2.3',
      'n99Rn': '',
      'iscs': '',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-05',
      'avgTa': '2.4',
      'minTa': '-2.5',
      'minTaHrmt': '0617',
      'maxTa': '7.6',
      'maxTaHrmt': '1528',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '5.5',
      'maxInsWsWd': '20',
      'maxInsWsHrmt': '1407',
      'maxWs': '3.5',
      'maxWsWd': '20',
      'maxWsHrmt': '1426',
      'avgWs': '0.8',
      'hr24SumRws': '723',
      'maxWd': '360',
      'avgTd': '-6.8',
      'minRhm': '38',
      'minRhmHrmt': '1236',
      'avgRhm': '51.5',
      'avgPv': '3.7',
      'avgPa': '1025.2',
      'maxPs': '1032.3',
      'maxPsHrmt': '0959',
      'minPs': '1027.6',
      'minPsHrmt': '1439',
      'avgPs': '1029.6',
      'ssDur': '9.9',
      'sumSsHr': '5.7',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.54',
      'sumGsr': '7.42',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '3.4',
      'avgLmac': '1.4',
      'avgTs': '0.3',
      'minTg': '-7.7',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.1',
      'sumSmlEv': '1.5',
      'n99Rn': '',
      'iscs': '{연무}1211-{연무}{강도0}1500-{연무}{강도0}1800-{연무}{강도0}2100-{연무}{강도0}2400-',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-06',
      'avgTa': '3.4',
      'minTa': '-1.5',
      'minTaHrmt': '0725',
      'maxTa': '9.0',
      'maxTaHrmt': '1455',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '0.67',
      'sumRn': '0.1',
      'maxInsWs': '5.4',
      'maxInsWsWd': '20',
      'maxInsWsHrmt': '0558',
      'maxWs': '3.0',
      'maxWsWd': '50',
      'maxWsHrmt': '1043',
      'avgWs': '1.1',
      'hr24SumRws': '916',
      'maxWd': '20',
      'avgTd': '-5.4',
      'minRhm': '25',
      'minRhmHrmt': '1515',
      'avgRhm': '54.8',
      'avgPv': '4.1',
      'avgPa': '1018.0',
      'maxPs': '1028.3',
      'maxPsHrmt': '0001',
      'minPs': '1016.6',
      'minPsHrmt': '2338',
      'avgPs': '1022.4',
      'ssDur': '9.9',
      'sumSsHr': '7.9',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.77',
      'sumGsr': '9.72',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '3.4',
      'avgLmac': '1.8',
      'avgTs': '1.8',
      'minTg': '-6.7',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.5',
      'sumSmlEv': '2.1',
      'n99Rn': '',
      'iscs': '-{연무}-{연무}{강도0}0300-{연무}{강도0}0600-{연무}{강도0}0900-{연무}{강도0}1200-1241. {연무}2112-2345. {비}2319-2359. {박무}2340-{박무}{강도0}2400-',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-07',
      'avgTa': '4.8',
      'minTa': '1.5',
      'minTaHrmt': '2342',
      'maxTa': '8.5',
      'maxTaHrmt': '1326',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '10.8',
      'maxInsWsWd': '270',
      'maxInsWsHrmt': '0852',
      'maxWs': '3.5',
      'maxWsWd': '290',
      'maxWsHrmt': '0442',
      'avgWs': '1.5',
      'hr24SumRws': '1277',
      'maxWd': '270',
      'avgTd': '-6.1',
      'minRhm': '29',
      'minRhmHrmt': '1413',
      'avgRhm': '46.4',
      'avgPv': '3.9',
      'avgPa': '1014.1',
      'maxPs': '1023.4',
      'maxPsHrmt': '2359',
      'minPs': '1014.4',
      'minPsHrmt': '0354',
      'avgPs': '1018.4',
      'ssDur': '9.9',
      'sumSsHr': '6.8',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.68',
      'sumGsr': '8.46',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '0.5',
      'avgLmac': '0.5',
      'avgTs': '2.0',
      'minTg': '-5.6',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.5',
      'sumSmlEv': '2.1',
      'n99Rn': '',
      'iscs': '-{박무}-{박무}{강도0}0300-0311. {연무}0305-{연무}{강도0}0600- 0755.{황사}0755-{황사}{강도1}0900-{황사}{강도0}1200-1450.',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-08',
      'avgTa': '3.3',
      'minTa': '-1.2',
      'minTaHrmt': '0733',
      'maxTa': '9.8',
      'maxTaHrmt': '1422',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '5.5',
      'maxInsWsWd': '20',
      'maxInsWsHrmt': '0913',
      'maxWs': '3.1',
      'maxWsWd': '50',
      'maxWsHrmt': '1040',
      'avgWs': '1.1',
      'hr24SumRws': '941',
      'maxWd': '20',
      'avgTd': '-6.2',
      'minRhm': '29',
      'minRhmHrmt': '1312',
      'avgRhm': '51.4',
      'avgPv': '3.9',
      'avgPa': '1020.1',
      'maxPs': '1026.9',
      'maxPsHrmt': '0953',
      'minPs': '1022.9',
      'minPsHrmt': '1400',
      'avgPs': '1024.6',
      'ssDur': '9.9',
      'sumSsHr': '8.8',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.85',
      'sumGsr': '10.51',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '0.1',
      'avgLmac': '0.0',
      'avgTs': '1.9',
      'minTg': '-7.5',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.3',
      'sumSmlEv': '1.9',
      'n99Rn': '',
      'iscs': '{연무}0611-{연무}{강도0}0900-0937.',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-09',
      'avgTa': '6.5',
      'minTa': '0.1',
      'minTaHrmt': '0431',
      'maxTa': '14.2',
      'maxTaHrmt': '1526',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '7.1',
      'maxInsWsWd': '340',
      'maxInsWsHrmt': '2112',
      'maxWs': '3.4',
      'maxWsWd': '70',
      'maxWsHrmt': '1846',
      'avgWs': '0.9',
      'hr24SumRws': '804',
      'maxWd': '90',
      'avgTd': '-2.1',
      'minRhm': '40',
      'minRhmHrmt': '1712',
      'avgRhm': '54.5',
      'avgPv': '5.4',
      'avgPa': '1018.3',
      'maxPs': '1025.5',
      'maxPsHrmt': '2334',
      'minPs': '1019.3',
      'minPsHrmt': '1432',
      'avgPs': '1022.6',
      'ssDur': '9.9',
      'sumSsHr': '8.0',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.73',
      'sumGsr': '9.13',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '0.6',
      'avgLmac': '0.6',
      'avgTs': '3.4',
      'minTg': '-6.1',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.5',
      'sumSmlEv': '2.2',
      'n99Rn': '',
      'iscs': '',
      'sumFogDur': ''},
     {'stnId': '155',
      'stnNm': '창원',
      'tm': '2023-01-10',
      'avgTa': '5.2',
      'minTa': '-0.5',
      'minTaHrmt': '0718',
      'maxTa': '10.9',
      'maxTaHrmt': '1403',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '5.0',
      'maxInsWsWd': '360',
      'maxInsWsHrmt': '0201',
      'maxWs': '3.5',
      'maxWsWd': '110',
      'maxWsHrmt': '1438',
      'avgWs': '1.1',
      'hr24SumRws': '972',
      'maxWd': '50',
      'avgTd': '-3.8',
      'minRhm': '39',
      'minRhmHrmt': '1144',
      'avgRhm': '52.9',
      'avgPv': '4.7',
      'avgPa': '1023.4',
      'maxPs': '1030.2',
      'maxPsHrmt': '0921',
      'minPs': '1025.4',
      'minPsHrmt': '0001',
      'avgPs': '1027.8',
      'ssDur': '10.0',
      'sumSsHr': '8.6',
      'hr1MaxIcsrHrmt': '1200',
      'hr1MaxIcsr': '1.88',
      'sumGsr': '10.76',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '1.8',
      'avgLmac': '0.0',
      'avgTs': '3.7',
      'minTg': '-6.8',
      'avgCm5Te': '',
      'avgCm10Te': '',
      'avgCm20Te': '',
      'avgCm30Te': '',
      'avgM05Te': '',
      'avgM10Te': '',
      'avgM15Te': '',
      'avgM30Te': '',
      'avgM50Te': '',
      'sumLrgEv': '1.5',
      'sumSmlEv': '2.1',
      'n99Rn': '',
      'iscs': '',
      'sumFogDur': ''}]},
   'pageNo': 1,
   'numOfRows': 10,
   'totalCount': 218}}}

In [26]:
# 6. 전체 조회데이터 건수를 이용한 데이터 한페이지 출력
params['numOfRows'] = weather['response']['body']['totalCount']
response = requests.get(url, params=params)

weather = json.loads(response.content)
weather['response']['body']['items']['item'][0]

{'stnId': '155',
 'stnNm': '창원',
 'tm': '2023-01-01',
 'avgTa': '2.4',
 'minTa': '-3.0',
 'minTaHrmt': '0544',
 'maxTa': '7.2',
 'maxTaHrmt': '1443',
 'mi10MaxRn': '',
 'mi10MaxRnHrmt': '',
 'hr1MaxRn': '',
 'hr1MaxRnHrmt': '',
 'sumRnDur': '',
 'sumRn': '',
 'maxInsWs': '6.2',
 'maxInsWsWd': '20',
 'maxInsWsHrmt': '1347',
 'maxWs': '4.0',
 'maxWsWd': '50',
 'maxWsHrmt': '1348',
 'avgWs': '1.3',
 'hr24SumRws': '1087',
 'maxWd': '50',
 'avgTd': '-9.0',
 'minRhm': '21',
 'minRhmHrmt': '2025',
 'avgRhm': '45.1',
 'avgPv': '3.2',
 'avgPa': '1024.4',
 'maxPs': '1030.6',
 'maxPsHrmt': '0954',
 'minPs': '1026.4',
 'minPsHrmt': '1536',
 'avgPs': '1028.9',
 'ssDur': '9.8',
 'sumSsHr': '8.5',
 'hr1MaxIcsrHrmt': '1200',
 'hr1MaxIcsr': '1.72',
 'sumGsr': '9.24',
 'ddMefs': '',
 'ddMefsHrmt': '',
 'ddMes': '',
 'ddMesHrmt': '',
 'sumDpthFhsc': '',
 'avgTca': '1.9',
 'avgLmac': '0.0',
 'avgTs': '0.3',
 'minTg': '-7.7',
 'avgCm5Te': '',
 'avgCm10Te': '',
 'avgCm20Te': '',
 'avgCm30Te': '',
 'avgM05Te': '',
 'avgM10Te': '',
 'avgM15Te': '',
 'avgM30Te': '',
 'avgM50Te': '',
 'sumLrgEv': '1.7',
 'sumSmlEv': '2.4',
 'n99Rn': '',
 'iscs': '{연무}1334-{연무}{강도0}1500-1756.',
 'sumFogDur': ''}

In [27]:
#7. 조회데이터 전체 DataFrame으로 만들기
weather_df = pd.DataFrame(weather['response']['body']['items']['item'])
weather_df.head(3)

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
0,155,창원,2023-01-01,2.4,-3.0,0544,7.2,1443,,,...,,,,,,1.7,2.4,,{연무}1334-{연무}{강도0}1500-1756.,
1,155,창원,2023-01-02,1.3,-0.9,2356,4.6,1538,,,...,,,,,,2.0,2.8,,,
2,155,창원,2023-01-03,0.4,-2.7,0736,4.9,1303,,,...,,,,,,1.9,2.7,,,

In [31]:
#8. 분석에 필요한 데이터 추출(일자/지점명/평균기온/최저기온/최고기온/일강수량)
wt_df=weather_df[['tm','stnNm','avgTa','minTa','maxTa','sumRn']].copy()
wt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tm      218 non-null    object
 1   stnNm   218 non-null    object
 2   avgTa   218 non-null    object
 3   minTa   218 non-null    object
 4   maxTa   218 non-null    object
 5   sumRn   218 non-null    object
dtypes: object(6)
memory usage: 10.3+ KB

#### 기상청 API를 이용한 전체데이터(1904년~) 가져오기

In [1]:
# 지점명을 이용한 지점코드 찾기
def loc_code_sch(loc_name):
    loc_code = pd.read_csv('./기상청위치코드.csv', encoding='utf-8')
    loc_code=loc_code[loc_code['지점명']==loc_name]['지점'].values[0]
    #print(loc_code)
    return str(loc_code)

In [129]:
# Weather API 함수 생성
def weather_api(startDt, endDt, stnIds, numOfRows=10):
    
    # 기상청 API 호출을 위한 기본 정보 설정
    url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'
    params ={'serviceKey' : 'V2soxVa/BMDzYDIk9IbGZTgcZeSQ6GIdaZnsBoez7GPAUwIQ/6MT/jyI5mtbTgXy24zNvlE9d5/EF0Y0YoKoNQ==', 
            'pageNo' : '1', 
            'numOfRows' : numOfRows, 
            'dataType' : 'JSON', 
            'dataCd' : 'ASOS', 
            'dateCd' : 'DAY', 
            'startDt' : startDt, # 20210101
            'endDt' : endDt, 
            'stnIds' : stnIds }
    
    # 기상청 데이터 조회
    response = requests.get(url, params=params)  # API 호출
    if response.status_code != 200:        # 정상적으로 호출되지 않은 경우
        exit('API 호출 에러: ' + response.status_code)
        
    try:
        weather_res = json.loads(response.content)       # 결과를 json 형태(딕셔너리형)로 변환
    except:
        print(weather_res.content)
        exit()
        
    return weather_res   # 결과 반환

In [130]:
from datetime import date, datetime, timedelta   # 날짜/시간 관련 모듈
import tqdm   # 진행바 모듈

# 사용자로부터 데이터 입력 받기
startDT = input('시작일(yyyymmdd): ')  # 시작일(20150601)
endDT = input('종료일(yyyymmdd): ')    # 종료일(20230808)

# 지역명으로 지점코드 조회
loc_name= input('지역을 입력하세요: ')
stnIds= loc_code_sch(loc_name)

108

In [131]:

# 데이터 추출
weather_df=pd.DataFrame()   # 최초 데이터프레임 생성
cnt = 0                     # 데이터 추출 횟수 카운트
today = date.today().strftime("%Y%m%d")      # 오늘 날짜 =>텍스트로 변환

for i in tqdm.tqdm(range(int(startDT[:4]), int(endDT[:4])+1)):
    if cnt !=0:     # 최초 데이터프레임 생성 후 2번째부터는 시작일과 종료일 변경
        startDTs = date(i, 1, 1).strftime("%Y%m%d")   # 시작일
    else:
        startDTs = startDT
    
    if i != int(endDT[:4]):     # 마지막 년도는 종료일로 설정
        endDTs = date(i, 12, 31).strftime("%Y%m%d")   # 종료일
    else:
        endDTs = endDT
    
    if int(endDTs) >= int(today):     # 오늘 날짜보다 종료일이 크면
        endDTs = int(date.today().strftime("%Y%m%d")) - 1   # 20230808-1 = 20230807
        endDTs = str(endDTs)  # 종료일 당일 전날로 변경후 텍스트로 변환
    
    weather_res = weather_api(startDTs, endDTs, stnIds)   # 함수 호출(최초)
    
    
    try:  # 지역이 없는 경우 에러 발생
        numOfRows = weather_res['response']['body']['totalCount']
    except:     
        continue  # 지역이 없는 경우 다음 년도로 넘어감
    
    weather_res = weather_api(startDTs, endDTs, stnIds, numOfRows)   # 함수 호출(전체 조회 데이터)
    df1 = pd.DataFrame(weather_res['response']['body']['items']['item'])  # 데이터프레임 생성
    weather_df = pd.concat([weather_df, df1], ignore_index=True)          # 데이터프레임 병합
    cnt += 1    # 데이터 추출 횟수 카운트
    
weather_df.info()

100%|██████████| 114/114 [09:58<00:00,  5.25s/it]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40650 entries, 0 to 40649
Data columns (total 62 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   stnId           40650 non-null  object
 1   stnNm           40650 non-null  object
 2   tm              40650 non-null  object
 3   avgTa           40650 non-null  object
 4   minTa           40650 non-null  object
 5   minTaHrmt       40650 non-null  object
 6   maxTa           40650 non-null  object
 7   maxTaHrmt       40650 non-null  object
 8   mi10MaxRn       40650 non-null  object
 9   mi10MaxRnHrmt   40650 non-null  object
 10  hr1MaxRn        40650 non-null  object
 11  hr1MaxRnHrmt    40650 non-null  object
 12  sumRnDur        40650 non-null  object
 13  sumRn           40650 non-null  object
 14  maxInsWs        40650 non-null  object
 15  maxInsWsWd      40650 non-null  object
 16  maxInsWsHrmt    40650 non-null  object
 17  maxWs           40650 non-null  object
 18  maxWsWd         40650 non-null  object
 19  maxWsHrmt       40650 non-null  object
 20  avgWs           40650 non-null  object
 21  hr24SumRws      40650 non-null  object
 22  maxWd           40650 non-null  object
 23  avgTd           40650 non-null  object
 24  minRhm          40650 non-null  object
 25  minRhmHrmt      40650 non-null  object
 26  avgRhm          40650 non-null  object
 27  avgPv           40650 non-null  object
 28  avgPa           40650 non-null  object
 29  maxPs           40650 non-null  object
 30  maxPsHrmt       40650 non-null  object
 31  minPs           40650 non-null  object
 32  minPsHrmt       40650 non-null  object
 33  avgPs           40650 non-null  object
 34  ssDur           40650 non-null  object
 35  sumSsHr         40650 non-null  object
 36  hr1MaxIcsrHrmt  40650 non-null  object
 37  hr1MaxIcsr      40650 non-null  object
 38  sumGsr          40650 non-null  object
 39  ddMefs          40650 non-null  object
 40  ddMefsHrmt      40650 non-null  object
 41  ddMes           40650 non-null  object
 42  ddMesHrmt       40650 non-null  object
 43  sumDpthFhsc     40650 non-null  object
 44  avgTca          40650 non-null  object
 45  avgLmac         40650 non-null  object
 46  avgTs           40650 non-null  object
 47  minTg           40650 non-null  object
 48  avgCm5Te        40650 non-null  object
 49  avgCm10Te       40650 non-null  object
 50  avgCm20Te       40650 non-null  object
 51  avgCm30Te       40650 non-null  object
 52  avgM05Te        40650 non-null  object
 53  avgM10Te        40650 non-null  object
 54  avgM15Te        40650 non-null  object
 55  avgM30Te        40650 non-null  object
 56  avgM50Te        40650 non-null  object
 57  sumLrgEv        40650 non-null  object
 58  sumSmlEv        40650 non-null  object
 59  n99Rn           40650 non-null  object
 60  iscs            40650 non-null  object
 61  sumFogDur       40650 non-null  object
dtypes: object(62)
memory usage: 19.2+ MB

In [118]:
weather_df.head()

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
0,108,서울,1910-01-01,-5.2,-6.6,,0.6,,,,...,,,,,,,0.8,,{눈}{강도0}0735-0746. {눈}{강도0}0943-0952. {눈}{강도...,
1,108,서울,1910-01-02,-7.2,-9.4,,-4.3,,,,...,,,,,,,2.2,,({눈} 1 cm),
2,108,서울,1910-01-03,-1.2,-8.2,,3.4,,,,...,,,,,,,1.5,,{싸락우박}{강도0}0515-0526.,
3,108,서울,1910-01-04,3.2,0.4,,8.0,,,,...,,,,,,,1.0,,{싸락우박}{강도0}0430-0458. {햇무리}{강도0}0425-0507.,
4,108,서울,1910-01-05,2.5,-0.3,,7.5,,,,...,,,,,,,1.7,,{안개}{강도0}0648-{안개}0736-{안개}{강도0}0925-1053. {비...,

In [99]:
weather_df.tail()

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
40645,108,서울,2023-08-02,29.7,26.8,0519,33.7,1436,,,...,28.2,25.8,24.6,19.5,16.3,5.4,7.7,,,
40646,108,서울,2023-08-03,29.5,25.8,0615,33.8,1446,,,...,28.3,25.9,24.7,19.5,16.3,5.4,7.7,,,
40647,108,서울,2023-08-04,30.0,26.5,0520,34.4,1634,,,...,28.3,26.0,24.8,19.5,16.3,5.2,7.5,,,
40648,108,서울,2023-08-05,30.3,26.4,0611,34.9,1548,,,...,28.5,26.1,24.9,19.6,16.4,5.6,8.0,,,
40649,108,서울,2023-08-06,29.8,27.0,1606,33.0,1403,3.7,1556,...,28.7,26.2,25.0,19.6,16.4,3.1,4.4,4.9,{소나기}1450-{소나기}{강도0}1500-1625.,

In [122]:
weather_df.to_csv('weather_seoul.csv', index=False)

In [123]:
#8. 분석에 필요한 데이터 추출(일자/지점명/평균기온/최저기온/최고기온/일강수량)
wt_df=weather_df[['tm','stnNm','avgTa','minTa','maxTa','sumRn']].copy()
wt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32762 entries, 0 to 32761
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tm      32762 non-null  object
 1   stnNm   32762 non-null  object
 2   avgTa   32762 non-null  object
 3   minTa   32762 non-null  object
 4   maxTa   32762 non-null  object
 5   sumRn   32762 non-null  object
dtypes: object(6)
memory usage: 1.5+ MB

In [125]:
wt_df.head()

           tm stnNm avgTa minTa maxTa sumRn
0  1910-01-01    서울  -5.2  -6.6   0.6   1.0
1  1910-01-02    서울  -7.2  -9.4  -4.3
2  1910-01-03    서울  -1.2  -8.2   3.4   0.0
3  1910-01-04    서울   3.2   0.4   8.0   0.0
4  1910-01-05    서울   2.5  -0.3   7.5   0.1

In [127]:
wt_df.isnull().sum()

tm       0
stnNm    0
avgTa    0
minTa    0
maxTa    0
sumRn    0
dtype: int64