In [68]:
# 1. 모듈 연결하기
import requests
import pandas as pd
import json

In [69]:
# 2. 기본정보 설정
url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'
params ={'serviceKey' : 'V2soxVa/BMDzYDIk9IbGZTgcZeSQ6GIdaZnsBoez7GPAUwIQ/6MT/jyI5mtbTgXy24zNvlE9d5/EF0Y0YoKoNQ==', 
         'pageNo' : '1', 
         'numOfRows' : '10', 
         'dataType' : 'JSON', 
         'dataCd' : 'ASOS', 
         'dateCd' : 'DAY', 
         'startDt' : '20100101', 
         'endDt' : '20100806', 
         'stnIds' : '108' }

In [70]:
# 지점명 찾기
def loc_code_sch(loc_name):
    loc_code = pd.read_csv('./기상청위치코드.csv', encoding='utf-8')
    loc_code=loc_code[loc_code['지점명']==loc_name]['지점'].values[0]
    return str(loc_code)

In [71]:
# 3. 검색 지역 코드 확인
startDT=input('시작일자를 입력하세요 (yyyymmdd): ')
endDT=input('종료일자를 입력하세요 (yyyymmdd): ')
location=input('지역을 입력하세요: ')
loc_code=loc_code_sch(location)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
# 4. 사용자가 입력받은 조건으로 기상청에 데이터 요청하기
params['startDt'] = startDT
params['endDt'] = endDT
params['stnIds'] = loc_code

params

{'serviceKey': 'V2soxVa/BMDzYDIk9IbGZTgcZeSQ6GIdaZnsBoez7GPAUwIQ/6MT/jyI5mtbTgXy24zNvlE9d5/EF0Y0YoKoNQ==',
 'pageNo': '1',
 'numOfRows': 2,
 'dataType': 'JSON',
 'dataCd': 'ASOS',
 'dateCd': 'DAY',
 'startDt': '20230601',
 'endDt': '20230802',
 'stnIds': '108',
 'endDT': '20230802'}

In [ ]:
# 5. 기상청 조회 일자별 데이터 가져오기
response = requests.get(url, params=params)

weather = json.loads(response.content)
weather

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL_SERVICE'},
  'body': {'dataType': 'JSON',
   'items': {'item': [{'stnId': '108',
      'stnNm': '서울',
      'tm': '2023-06-01',
      'avgTa': '22.8',
      'minTa': '19.7',
      'minTaHrmt': '0528',
      'maxTa': '26.3',
      'maxTaHrmt': '1707',
      'mi10MaxRn': '',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '',
      'sumRn': '',
      'maxInsWs': '5.7',
      'maxInsWsWd': '340',
      'maxInsWsHrmt': '1634',
      'maxWs': '3.4',
      'maxWsWd': '270',
      'maxWsHrmt': '2152',
      'avgWs': '1.9',
      'hr24SumRws': '1612',
      'maxWd': '290',
      'avgTd': '16.1',
      'minRhm': '56',
      'minRhmHrmt': '1833',
      'avgRhm': '66.9',
      'avgPv': '18.3',
      'avgPa': '995.6',
      'maxPs': '1009.3',
      'maxPsHrmt': '0001',
      'minPs': '1002.1',
      'minPsHrmt': '1742',
      'avgPs': '1005.3',
      'ssDur': '14.6',
      'sumSsHr': '2.2',
      'hr1MaxIcsrHrmt': '1100',
      'hr1MaxIcsr': '2.32',
      'sumGsr': '15.18',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '8.3',
      'avgLmac': '3.6',
      'avgTs': '24.3',
      'minTg': '17.1',
      'avgCm5Te': '23.5',
      'avgCm10Te': '23.1',
      'avgCm20Te': '22.4',
      'avgCm30Te': '22.0',
      'avgM05Te': '21.9',
      'avgM10Te': '19.1',
      'avgM15Te': '18.0',
      'avgM30Te': '13.8',
      'avgM50Te': '13.8',
      'sumLrgEv': '3.0',
      'sumSmlEv': '4.3',
      'n99Rn': '',
      'iscs': '',
      'sumFogDur': ''},
     {'stnId': '108',
      'stnNm': '서울',
      'tm': '2023-06-02',
      'avgTa': '20.4',
      'minTa': '17.9',
      'minTaHrmt': '0601',
      'maxTa': '25.0',
      'maxTaHrmt': '1648',
      'mi10MaxRn': '0.0',
      'mi10MaxRnHrmt': '',
      'hr1MaxRn': '0.0',
      'hr1MaxRnHrmt': '',
      'sumRnDur': '0.17',
      'sumRn': '0.0',
      'maxInsWs': '7.0',
      'maxInsWsWd': '250',
      'maxInsWsHrmt': '1712',
      'maxWs': '4.7',
      'maxWsWd': '250',
      'maxWsHrmt': '1853',
      'avgWs': '2.3',
      'hr24SumRws': '2019',
      'maxWd': '250',
      'avgTd': '16.1',
      'minRhm': '59',
      'minRhmHrmt': '1636',
      'avgRhm': '77.4',
      'avgPv': '18.3',
      'avgPa': '992.5',
      'maxPs': '1005.1',
      'maxPsHrmt': '2356',
      'minPs': '1000.7',
      'minPsHrmt': '1621',
      'avgPs': '1002.3',
      'ssDur': '14.6',
      'sumSsHr': '5.2',
      'hr1MaxIcsrHrmt': '1400',
      'hr1MaxIcsr': '2.85',
      'sumGsr': '14.24',
      'ddMefs': '',
      'ddMefsHrmt': '',
      'ddMes': '',
      'ddMesHrmt': '',
      'sumDpthFhsc': '',
      'avgTca': '3.5',
      'avgLmac': '3.1',
      'avgTs': '23.3',
      'minTg': '13.9',
      'avgCm5Te': '22.6',
      'avgCm10Te': '22.3',
      'avgCm20Te': '21.7',
      'avgCm30Te': '21.7',
      'avgM05Te': '21.8',
      'avgM10Te': '19.2',
      'avgM15Te': '18.1',
      'avgM30Te': '13.9',
      'avgM50Te': '13.8',
      'sumLrgEv': '3.0',
      'sumSmlEv': '4.3',
      'n99Rn': '0.0',
      'iscs': '{박무}0655-0735. {안개비}1310-1320.',
      'sumFogDur': ''}]},
   'pageNo': 1,
   'numOfRows': 2,
   'totalCount': 63}}}

In [ ]:
# 6. 전체 조회 데이터 건수를 이용한 데이터 한페이지 출력
params['numOfRows'] = weather['response']['body']['totalCount']
response = requests.get(url, params=params)

weather = json.loads(response.content)
weather['response']['body']['items']['item'][0]

{'stnId': '108',
 'stnNm': '서울',
 'tm': '2023-06-01',
 'avgTa': '22.8',
 'minTa': '19.7',
 'minTaHrmt': '0528',
 'maxTa': '26.3',
 'maxTaHrmt': '1707',
 'mi10MaxRn': '',
 'mi10MaxRnHrmt': '',
 'hr1MaxRn': '',
 'hr1MaxRnHrmt': '',
 'sumRnDur': '',
 'sumRn': '',
 'maxInsWs': '5.7',
 'maxInsWsWd': '340',
 'maxInsWsHrmt': '1634',
 'maxWs': '3.4',
 'maxWsWd': '270',
 'maxWsHrmt': '2152',
 'avgWs': '1.9',
 'hr24SumRws': '1612',
 'maxWd': '290',
 'avgTd': '16.1',
 'minRhm': '56',
 'minRhmHrmt': '1833',
 'avgRhm': '66.9',
 'avgPv': '18.3',
 'avgPa': '995.6',
 'maxPs': '1009.3',
 'maxPsHrmt': '0001',
 'minPs': '1002.1',
 'minPsHrmt': '1742',
 'avgPs': '1005.3',
 'ssDur': '14.6',
 'sumSsHr': '2.2',
 'hr1MaxIcsrHrmt': '1100',
 'hr1MaxIcsr': '2.32',
 'sumGsr': '15.18',
 'ddMefs': '',
 'ddMefsHrmt': '',
 'ddMes': '',
 'ddMesHrmt': '',
 'sumDpthFhsc': '',
 'avgTca': '8.3',
 'avgLmac': '3.6',
 'avgTs': '24.3',
 'minTg': '17.1',
 'avgCm5Te': '23.5',
 'avgCm10Te': '23.1',
 'avgCm20Te': '22.4',
 'avgCm30Te': '22.0',
 'avgM05Te': '21.9',
 'avgM10Te': '19.1',
 'avgM15Te': '18.0',
 'avgM30Te': '13.8',
 'avgM50Te': '13.8',
 'sumLrgEv': '3.0',
 'sumSmlEv': '4.3',
 'n99Rn': '',
 'iscs': '',
 'sumFogDur': ''}

In [ ]:
# 7. 조회데이터 전체 DataFrame으로 만들기
weather_df = pd.DataFrame(weather['response']['body']['items']['item'])
weather_df.head(3)

,stnId,stnNm,tm,avgTa,minTa,minTaHrmt,maxTa,maxTaHrmt,mi10MaxRn,mi10MaxRnHrmt,...,avgM05Te,avgM10Te,avgM15Te,avgM30Te,avgM50Te,sumLrgEv,sumSmlEv,n99Rn,iscs,sumFogDur
0,108,서울,2023-06-01,22.8,19.7,0528,26.3,1707,,,...,21.9,19.1,18.0,13.8,13.8,3.0,4.3,,,
1,108,서울,2023-06-02,20.4,17.9,0601,25.0,1648,0.0,,...,21.8,19.2,18.1,13.9,13.8,3.0,4.3,0.0,{박무}0655-0735. {안개비}1310-1320.,
2,108,서울,2023-06-03,22.0,16.6,0607,27.8,1423,,,...,21.5,19.3,18.2,14.0,13.8,6.8,9.7,,,

In [ ]:
# 8. 분석에 필요한 데이터 추출(일자 / 지점명 / 평균기온 / 최저기온 / 최고기온 / 일강수량)
wt_df=weather_df[['tm','stnNm','avgTa','minTa','maxTa','sumRn']]
#wt_df.head()
wt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tm      63 non-null     object
 1   stnNm   63 non-null     object
 2   avgTa   63 non-null     object
 3   minTa   63 non-null     object
 4   maxTa   63 non-null     object
 5   sumRn   63 non-null     object
dtypes: object(6)
memory usage: 3.1+ KB

### 기상청 API를 이용한 전체데이터(1904년~) 가져오기

In [ ]:
# 지점명 찾기
def loc_code_sch(loc_name):
    loc_code = pd.read_csv('./기상청위치코드.csv', encoding='utf-8')
    loc_code=loc_code[loc_code['지점명']==loc_name]['지점'].values[0]
    return str(loc_code)

In [ ]:
# Weather API 함수 생성
# 기본정보 설정

def weather_api(loc_name, startDt, endDt, numOfRows=10):
    loc_code_sch(loc_name)   #지역명으로 지점코드 조회
    
    # 기상청 API 호출을 위한 기본정보 설정
    url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'
    params ={'serviceKey' : 'V2soxVa/BMDzYDIk9IbGZTgcZeSQ6GIdaZnsBoez7GPAUwIQ/6MT/jyI5mtbTgXy24zNvlE9d5/EF0Y0YoKoNQ==', 
            'pageNo' : '1', 
            'numOfRows' : '10', 
            'dataType' : 'JSON', 
            'dataCd' : 'ASOS', 
            'dateCd' : 'DAY', 
            'startDt' : startDt, 
            'endDt' : endDt, 
            'stnIds' : loc_name }
    
    
    # 기상청 조회 일자별 데이터 가져오기
    response = requests.get(url, params=params)  # API 데이터 호출
    if response.status_code != 200:
        exit('API 호출 에러: ' + response.status_code)
        
    weather = json.loads(response.content)       # 결과를 json 형태로 변환(딕셔너리형)
    return weather

In [ ]:
# 최초 데이터 요청
startDT=input('시작일자를 입력하세요 (yyyymmdd): ')
endDT=input('종료일자를 입력하세요 (yyyymmdd): ')
loc_name=input('지역을 입력하세요: ')

wether_res = weather_api(loc_name, startDT, endDT)
numOfRows = wether_res['response']['body']['totalCount']

wether_res = weather_api(loc_name, startDt, endDt, numOfRows)
weather_df = pd.DataFrame(weather_res['response']['body']['items']['item'])
weather_df.info()

KeyError: 'body'